### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by steelbrain** [MicheleBertoli/react-worker#3]
Is it just me or the code is un-understandable for a person who hasn't wrote this.
If you could just provide an advance documentation of how it works, I would personally give you some chocolate. :chocolate_bar:

**Comment by MicheleBertoli** [comment]
Hey @steelbrain, thanks for the feedback.
I'm not sure the code is so unreadable because @sandropaganotti contributed to it without asking but I understand that documentation is important (http://thisisnotdocumentation.tumblr.com) and I love chocolate :D 
Is there anything in particular that you found hard to read?

**Comment by steelbrain** [comment]
Nevermind, this morning I tried reading it again and it was much more readable than before. My Bad.
Here you go :chocolate_bar:
